/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.30.2
 * source: v1/schedule/schedule.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\..\\google\\protobuf\\timestamp";
import * as dependency_2 from "./..\\..\\google\\protobuf\\empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace schedule {
    export class CreateScheduleRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedules?: Schedule[];
            force?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedules" in data && data.schedules != undefined) {
                    this.schedules = data.schedules;
                }
                if ("force" in data && data.force != undefined) {
                    this.force = data.force;
                }
            }
        }
        get schedules() {
            return pb_1.Message.getRepeatedWrapperField(this, Schedule, 1) as Schedule[];
        }
        set schedules(value: Schedule[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        get force() {
            return pb_1.Message.getFieldWithDefault(this, 2, false) as boolean;
        }
        set force(value: boolean) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            schedules?: ReturnType<typeof Schedule.prototype.toObject>[];
            force?: boolean;
        }): CreateScheduleRequest {
            const message = new CreateScheduleRequest({});
            if (data.schedules != null) {
                message.schedules = data.schedules.map(item => Schedule.fromObject(item));
            }
            if (data.force != null) {
                message.force = data.force;
            }
            return message;
        }
        toObject() {
            const data: {
                schedules?: ReturnType<typeof Schedule.prototype.toObject>[];
                force?: boolean;
            } = {};
            if (this.schedules != null) {
                data.schedules = this.schedules.map((item: Schedule) => item.toObject());
            }
            if (this.force != null) {
                data.force = this.force;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedules.length)
                writer.writeRepeatedMessage(1, this.schedules, (item: Schedule) => item.serialize(writer));
            if (this.force != false)
                writer.writeBool(2, this.force);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): CreateScheduleRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new CreateScheduleRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.schedules, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Schedule.deserialize(reader), Schedule));
                        break;
                    case 2:
                        message.force = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): CreateScheduleRequest {
            return CreateScheduleRequest.deserialize(bytes);
        }
    }
    export class GetScheduleRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedule_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedule_id" in data && data.schedule_id != undefined) {
                    this.schedule_id = data.schedule_id;
                }
            }
        }
        get schedule_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set schedule_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            schedule_id?: string;
        }): GetScheduleRequest {
            const message = new GetScheduleRequest({});
            if (data.schedule_id != null) {
                message.schedule_id = data.schedule_id;
            }
            return message;
        }
        toObject() {
            const data: {
                schedule_id?: string;
            } = {};
            if (this.schedule_id != null) {
                data.schedule_id = this.schedule_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedule_id.length)
                writer.writeString(1, this.schedule_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetScheduleRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetScheduleRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.schedule_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetScheduleRequest {
            return GetScheduleRequest.deserialize(bytes);
        }
    }
    export class ListScheduleRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedule_ids?: string[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedule_ids" in data && data.schedule_ids != undefined) {
                    this.schedule_ids = data.schedule_ids;
                }
            }
        }
        get schedule_ids() {
            return pb_1.Message.getFieldWithDefault(this, 1, []) as string[];
        }
        set schedule_ids(value: string[]) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            schedule_ids?: string[];
        }): ListScheduleRequest {
            const message = new ListScheduleRequest({});
            if (data.schedule_ids != null) {
                message.schedule_ids = data.schedule_ids;
            }
            return message;
        }
        toObject() {
            const data: {
                schedule_ids?: string[];
            } = {};
            if (this.schedule_ids != null) {
                data.schedule_ids = this.schedule_ids;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedule_ids.length)
                writer.writeRepeatedString(1, this.schedule_ids);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListScheduleRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListScheduleRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        pb_1.Message.addToRepeatedField(message, 1, reader.readString());
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListScheduleRequest {
            return ListScheduleRequest.deserialize(bytes);
        }
    }
    export class ListScheduleResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedules?: Schedule[];
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedules" in data && data.schedules != undefined) {
                    this.schedules = data.schedules;
                }
            }
        }
        get schedules() {
            return pb_1.Message.getRepeatedWrapperField(this, Schedule, 1) as Schedule[];
        }
        set schedules(value: Schedule[]) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data: {
            schedules?: ReturnType<typeof Schedule.prototype.toObject>[];
        }): ListScheduleResponse {
            const message = new ListScheduleResponse({});
            if (data.schedules != null) {
                message.schedules = data.schedules.map(item => Schedule.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data: {
                schedules?: ReturnType<typeof Schedule.prototype.toObject>[];
            } = {};
            if (this.schedules != null) {
                data.schedules = this.schedules.map((item: Schedule) => item.toObject());
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedules.length)
                writer.writeRepeatedMessage(1, this.schedules, (item: Schedule) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ListScheduleResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ListScheduleResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.schedules, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Schedule.deserialize(reader), Schedule));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ListScheduleResponse {
            return ListScheduleResponse.deserialize(bytes);
        }
    }
    export class UpdateScheduleRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): UpdateScheduleRequest {
            const message = new UpdateScheduleRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateScheduleRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateScheduleRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UpdateScheduleRequest {
            return UpdateScheduleRequest.deserialize(bytes);
        }
    }
    export class DeleteScheduleRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            schedule_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("schedule_id" in data && data.schedule_id != undefined) {
                    this.schedule_id = data.schedule_id;
                }
            }
        }
        get schedule_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set schedule_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            schedule_id?: string;
        }): DeleteScheduleRequest {
            const message = new DeleteScheduleRequest({});
            if (data.schedule_id != null) {
                message.schedule_id = data.schedule_id;
            }
            return message;
        }
        toObject() {
            const data: {
                schedule_id?: string;
            } = {};
            if (this.schedule_id != null) {
                data.schedule_id = this.schedule_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.schedule_id.length)
                writer.writeString(1, this.schedule_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteScheduleRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteScheduleRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.schedule_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteScheduleRequest {
            return DeleteScheduleRequest.deserialize(bytes);
        }
    }
    export class Schedule extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            departament_id?: string;
            day_of_week?: number;
            hour?: number;
            minute?: number;
            video_id?: string;
            create_at?: dependency_1.google.protobuf.Timestamp;
            update_at?: dependency_1.google.protobuf.Timestamp;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("departament_id" in data && data.departament_id != undefined) {
                    this.departament_id = data.departament_id;
                }
                if ("day_of_week" in data && data.day_of_week != undefined) {
                    this.day_of_week = data.day_of_week;
                }
                if ("hour" in data && data.hour != undefined) {
                    this.hour = data.hour;
                }
                if ("minute" in data && data.minute != undefined) {
                    this.minute = data.minute;
                }
                if ("video_id" in data && data.video_id != undefined) {
                    this.video_id = data.video_id;
                }
                if ("create_at" in data && data.create_at != undefined) {
                    this.create_at = data.create_at;
                }
                if ("update_at" in data && data.update_at != undefined) {
                    this.update_at = data.update_at;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get departament_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set departament_id(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get day_of_week() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set day_of_week(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get hour() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set hour(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get minute() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set minute(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get video_id() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set video_id(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get create_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 7) as dependency_1.google.protobuf.Timestamp;
        }
        set create_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 7, value);
        }
        get has_create_at() {
            return pb_1.Message.getField(this, 7) != null;
        }
        get update_at() {
            return pb_1.Message.getWrapperField(this, dependency_1.google.protobuf.Timestamp, 8) as dependency_1.google.protobuf.Timestamp;
        }
        set update_at(value: dependency_1.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 8, value);
        }
        get has_update_at() {
            return pb_1.Message.getField(this, 8) != null;
        }
        static fromObject(data: {
            id?: string;
            departament_id?: string;
            day_of_week?: number;
            hour?: number;
            minute?: number;
            video_id?: string;
            create_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            update_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
        }): Schedule {
            const message = new Schedule({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.departament_id != null) {
                message.departament_id = data.departament_id;
            }
            if (data.day_of_week != null) {
                message.day_of_week = data.day_of_week;
            }
            if (data.hour != null) {
                message.hour = data.hour;
            }
            if (data.minute != null) {
                message.minute = data.minute;
            }
            if (data.video_id != null) {
                message.video_id = data.video_id;
            }
            if (data.create_at != null) {
                message.create_at = dependency_1.google.protobuf.Timestamp.fromObject(data.create_at);
            }
            if (data.update_at != null) {
                message.update_at = dependency_1.google.protobuf.Timestamp.fromObject(data.update_at);
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                departament_id?: string;
                day_of_week?: number;
                hour?: number;
                minute?: number;
                video_id?: string;
                create_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
                update_at?: ReturnType<typeof dependency_1.google.protobuf.Timestamp.prototype.toObject>;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.departament_id != null) {
                data.departament_id = this.departament_id;
            }
            if (this.day_of_week != null) {
                data.day_of_week = this.day_of_week;
            }
            if (this.hour != null) {
                data.hour = this.hour;
            }
            if (this.minute != null) {
                data.minute = this.minute;
            }
            if (this.video_id != null) {
                data.video_id = this.video_id;
            }
            if (this.create_at != null) {
                data.create_at = this.create_at.toObject();
            }
            if (this.update_at != null) {
                data.update_at = this.update_at.toObject();
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.departament_id.length)
                writer.writeString(2, this.departament_id);
            if (this.day_of_week != 0)
                writer.writeInt32(3, this.day_of_week);
            if (this.hour != 0)
                writer.writeInt32(4, this.hour);
            if (this.minute != 0)
                writer.writeInt32(5, this.minute);
            if (this.video_id.length)
                writer.writeString(6, this.video_id);
            if (this.has_create_at)
                writer.writeMessage(7, this.create_at, () => this.create_at.serialize(writer));
            if (this.has_update_at)
                writer.writeMessage(8, this.update_at, () => this.update_at.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Schedule {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Schedule();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.departament_id = reader.readString();
                        break;
                    case 3:
                        message.day_of_week = reader.readInt32();
                        break;
                    case 4:
                        message.hour = reader.readInt32();
                        break;
                    case 5:
                        message.minute = reader.readInt32();
                        break;
                    case 6:
                        message.video_id = reader.readString();
                        break;
                    case 7:
                        reader.readMessage(message.create_at, () => message.create_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 8:
                        reader.readMessage(message.update_at, () => message.update_at = dependency_1.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Schedule {
            return Schedule.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedScheduleServiceService {
        static definition = {
            CreateSchedule: {
                path: "/schedule.ScheduleService/CreateSchedule",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: CreateScheduleRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => CreateScheduleRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Schedule) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Schedule.deserialize(new Uint8Array(bytes))
            },
            GetSchedule: {
                path: "/schedule.ScheduleService/GetSchedule",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetScheduleRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetScheduleRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Schedule) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Schedule.deserialize(new Uint8Array(bytes))
            },
            ListSchedule: {
                path: "/schedule.ScheduleService/ListSchedule",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: ListScheduleRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => ListScheduleRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: ListScheduleResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => ListScheduleResponse.deserialize(new Uint8Array(bytes))
            },
            UpdateSchedule: {
                path: "/schedule.ScheduleService/UpdateSchedule",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: UpdateScheduleRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => UpdateScheduleRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Schedule) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Schedule.deserialize(new Uint8Array(bytes))
            },
            DeleteSchedule: {
                path: "/schedule.ScheduleService/DeleteSchedule",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: DeleteScheduleRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => DeleteScheduleRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_2.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_2.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CreateSchedule(call: grpc_1.ServerUnaryCall<CreateScheduleRequest, Schedule>, callback: grpc_1.sendUnaryData<Schedule>): void;
        abstract GetSchedule(call: grpc_1.ServerUnaryCall<GetScheduleRequest, Schedule>, callback: grpc_1.sendUnaryData<Schedule>): void;
        abstract ListSchedule(call: grpc_1.ServerUnaryCall<ListScheduleRequest, ListScheduleResponse>, callback: grpc_1.sendUnaryData<ListScheduleResponse>): void;
        abstract UpdateSchedule(call: grpc_1.ServerUnaryCall<UpdateScheduleRequest, Schedule>, callback: grpc_1.sendUnaryData<Schedule>): void;
        abstract DeleteSchedule(call: grpc_1.ServerUnaryCall<DeleteScheduleRequest, dependency_2.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_2.google.protobuf.Empty>): void;
    }
    export class ScheduleServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedScheduleServiceService.definition, "ScheduleService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CreateSchedule: GrpcUnaryServiceInterface<CreateScheduleRequest, Schedule> = (message: CreateScheduleRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, callback?: grpc_1.requestCallback<Schedule>): grpc_1.ClientUnaryCall => {
            return super.CreateSchedule(message, metadata, options, callback);
        };
        GetSchedule: GrpcUnaryServiceInterface<GetScheduleRequest, Schedule> = (message: GetScheduleRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, callback?: grpc_1.requestCallback<Schedule>): grpc_1.ClientUnaryCall => {
            return super.GetSchedule(message, metadata, options, callback);
        };
        ListSchedule: GrpcUnaryServiceInterface<ListScheduleRequest, ListScheduleResponse> = (message: ListScheduleRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<ListScheduleResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<ListScheduleResponse>, callback?: grpc_1.requestCallback<ListScheduleResponse>): grpc_1.ClientUnaryCall => {
            return super.ListSchedule(message, metadata, options, callback);
        };
        UpdateSchedule: GrpcUnaryServiceInterface<UpdateScheduleRequest, Schedule> = (message: UpdateScheduleRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Schedule>, callback?: grpc_1.requestCallback<Schedule>): grpc_1.ClientUnaryCall => {
            return super.UpdateSchedule(message, metadata, options, callback);
        };
        DeleteSchedule: GrpcUnaryServiceInterface<DeleteScheduleRequest, dependency_2.google.protobuf.Empty> = (message: DeleteScheduleRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_2.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_2.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.DeleteSchedule(message, metadata, options, callback);
        };
    }
}
