/**
 * @fileoverview gRPC-Web generated client stub for schedule
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: v1/schedule/schedule.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as v1_schedule_schedule_pb from '../../v1/schedule/schedule_pb'; // proto import: "v1/schedule/schedule.proto"


export class ScheduleServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateSchedule = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/CreateSchedule',
    grpcWeb.MethodType.UNARY,
    v1_schedule_schedule_pb.CreateScheduleRequest,
    v1_schedule_schedule_pb.Schedule,
    (request: v1_schedule_schedule_pb.CreateScheduleRequest) => {
      return request.serializeBinary();
    },
    v1_schedule_schedule_pb.Schedule.deserializeBinary
  );

  createSchedule(
    request: v1_schedule_schedule_pb.CreateScheduleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_schedule_schedule_pb.Schedule>;

  createSchedule(
    request: v1_schedule_schedule_pb.CreateScheduleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void): grpcWeb.ClientReadableStream<v1_schedule_schedule_pb.Schedule>;

  createSchedule(
    request: v1_schedule_schedule_pb.CreateScheduleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/CreateSchedule',
        request,
        metadata || {},
        this.methodDescriptorCreateSchedule,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/CreateSchedule',
    request,
    metadata || {},
    this.methodDescriptorCreateSchedule);
  }

  methodDescriptorGetSchedule = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/GetSchedule',
    grpcWeb.MethodType.UNARY,
    v1_schedule_schedule_pb.GetScheduleRequest,
    v1_schedule_schedule_pb.Schedule,
    (request: v1_schedule_schedule_pb.GetScheduleRequest) => {
      return request.serializeBinary();
    },
    v1_schedule_schedule_pb.Schedule.deserializeBinary
  );

  getSchedule(
    request: v1_schedule_schedule_pb.GetScheduleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_schedule_schedule_pb.Schedule>;

  getSchedule(
    request: v1_schedule_schedule_pb.GetScheduleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void): grpcWeb.ClientReadableStream<v1_schedule_schedule_pb.Schedule>;

  getSchedule(
    request: v1_schedule_schedule_pb.GetScheduleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/GetSchedule',
        request,
        metadata || {},
        this.methodDescriptorGetSchedule,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/GetSchedule',
    request,
    metadata || {},
    this.methodDescriptorGetSchedule);
  }

  methodDescriptorListSchedule = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/ListSchedule',
    grpcWeb.MethodType.UNARY,
    v1_schedule_schedule_pb.ListScheduleRequest,
    v1_schedule_schedule_pb.ListScheduleResponse,
    (request: v1_schedule_schedule_pb.ListScheduleRequest) => {
      return request.serializeBinary();
    },
    v1_schedule_schedule_pb.ListScheduleResponse.deserializeBinary
  );

  listSchedule(
    request: v1_schedule_schedule_pb.ListScheduleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_schedule_schedule_pb.ListScheduleResponse>;

  listSchedule(
    request: v1_schedule_schedule_pb.ListScheduleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.ListScheduleResponse) => void): grpcWeb.ClientReadableStream<v1_schedule_schedule_pb.ListScheduleResponse>;

  listSchedule(
    request: v1_schedule_schedule_pb.ListScheduleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.ListScheduleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/ListSchedule',
        request,
        metadata || {},
        this.methodDescriptorListSchedule,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/ListSchedule',
    request,
    metadata || {},
    this.methodDescriptorListSchedule);
  }

  methodDescriptorUpdateSchedule = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/UpdateSchedule',
    grpcWeb.MethodType.UNARY,
    v1_schedule_schedule_pb.UpdateScheduleRequest,
    v1_schedule_schedule_pb.Schedule,
    (request: v1_schedule_schedule_pb.UpdateScheduleRequest) => {
      return request.serializeBinary();
    },
    v1_schedule_schedule_pb.Schedule.deserializeBinary
  );

  updateSchedule(
    request: v1_schedule_schedule_pb.UpdateScheduleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_schedule_schedule_pb.Schedule>;

  updateSchedule(
    request: v1_schedule_schedule_pb.UpdateScheduleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void): grpcWeb.ClientReadableStream<v1_schedule_schedule_pb.Schedule>;

  updateSchedule(
    request: v1_schedule_schedule_pb.UpdateScheduleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_schedule_schedule_pb.Schedule) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/UpdateSchedule',
        request,
        metadata || {},
        this.methodDescriptorUpdateSchedule,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/UpdateSchedule',
    request,
    metadata || {},
    this.methodDescriptorUpdateSchedule);
  }

  methodDescriptorDeleteSchedule = new grpcWeb.MethodDescriptor(
    '/schedule.ScheduleService/DeleteSchedule',
    grpcWeb.MethodType.UNARY,
    v1_schedule_schedule_pb.DeleteScheduleRequest,
    google_protobuf_empty_pb.Empty,
    (request: v1_schedule_schedule_pb.DeleteScheduleRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteSchedule(
    request: v1_schedule_schedule_pb.DeleteScheduleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteSchedule(
    request: v1_schedule_schedule_pb.DeleteScheduleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteSchedule(
    request: v1_schedule_schedule_pb.DeleteScheduleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/schedule.ScheduleService/DeleteSchedule',
        request,
        metadata || {},
        this.methodDescriptorDeleteSchedule,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/schedule.ScheduleService/DeleteSchedule',
    request,
    metadata || {},
    this.methodDescriptorDeleteSchedule);
  }

}

