/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/schedule/schedule.proto" (package "schedule", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Empty } from "../../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * Запрос на создание расписания.
 *
 * @generated from protobuf message schedule.CreateScheduleRequest
 */
export interface CreateScheduleRequest {
    /**
     * Расписания, которые необходимо создать.
     *
     * @generated from protobuf field: repeated schedule.Schedule schedules = 1;
     */
    schedules: Schedule[];
    /**
     * Флаг повторения расписания вновь и вновь.
     *
     * @generated from protobuf field: bool force = 2;
     */
    force: boolean;
}
/**
 * Запрос на получение расписания.
 *
 * @generated from protobuf message schedule.GetScheduleRequest
 */
export interface GetScheduleRequest {
    /**
     * ID расписания, которое необходимо получить.
     *
     * @generated from protobuf field: string schedule_id = 1;
     */
    scheduleId: string;
}
/**
 * Запрос на получение списка расписаний.
 *
 * @generated from protobuf message schedule.ListScheduleRequest
 */
export interface ListScheduleRequest {
    /**
     * ID расписания, которое необходимо получить.
     *
     * @generated from protobuf field: repeated string schedule_ids = 1;
     */
    scheduleIds: string[];
}
/**
 * Ответ на запрос списка расписаний.
 *
 * @generated from protobuf message schedule.ListScheduleResponse
 */
export interface ListScheduleResponse {
    /**
     * Список расписаний.
     *
     * @generated from protobuf field: repeated schedule.Schedule schedules = 1;
     */
    schedules: Schedule[];
}
/**
 * Запрос на обновление расписания.
 *
 * Нужно согласовать какие поля расписания можно менять.
 *
 * @generated from protobuf message schedule.UpdateScheduleRequest
 */
export interface UpdateScheduleRequest {
}
/**
 * Запрос на удаление расписания.
 *
 * @generated from protobuf message schedule.DeleteScheduleRequest
 */
export interface DeleteScheduleRequest {
    /**
     * ID расписания, которое необходимо удалить.
     *
     * @generated from protobuf field: string schedule_id = 1;
     */
    scheduleId: string;
}
/**
 * Струкутура расписания.
 *
 * @generated from protobuf message schedule.Schedule
 */
export interface Schedule {
    /**
     * ID расписания.
     *
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * ID отдела, для которого предназначено расписание.
     *
     * @generated from protobuf field: string departament_id = 2;
     */
    departamentId: string;
    /**
     * День недели (0 - воскресенье, 1 - понедельник, ..., 6 - суббота).
     *
     * @generated from protobuf field: int32 day_of_week = 3;
     */
    dayOfWeek: number;
    /**
     * Час времени.
     *
     * @generated from protobuf field: int32 hour = 4;
     */
    hour: number;
    /**
     * Минуты времени.
     *
     * @generated from protobuf field: int32 minute = 5;
     */
    minute: number;
    /**
     * ID видео, которое необходимо воспроизвести по расписанию.
     *
     * @generated from protobuf field: string video_id = 6;
     */
    videoId: string;
    /**
     * Время создания расписания.
     *
     * @generated from protobuf field: google.protobuf.Timestamp create_at = 7;
     */
    createAt?: Timestamp;
    /**
     * Время обновления расписания.
     *
     * @generated from protobuf field: google.protobuf.Timestamp update_at = 8;
     */
    updateAt?: Timestamp;
}
// @generated message type with reflection information, may provide speed optimized methods
class CreateScheduleRequest$Type extends MessageType<CreateScheduleRequest> {
    constructor() {
        super("schedule.CreateScheduleRequest", [
            { no: 1, name: "schedules", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Schedule },
            { no: 2, name: "force", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<CreateScheduleRequest>): CreateScheduleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.schedules = [];
        message.force = false;
        if (value !== undefined)
            reflectionMergePartial<CreateScheduleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateScheduleRequest): CreateScheduleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated schedule.Schedule schedules */ 1:
                    message.schedules.push(Schedule.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool force */ 2:
                    message.force = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateScheduleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated schedule.Schedule schedules = 1; */
        for (let i = 0; i < message.schedules.length; i++)
            Schedule.internalBinaryWrite(message.schedules[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool force = 2; */
        if (message.force !== false)
            writer.tag(2, WireType.Varint).bool(message.force);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.CreateScheduleRequest
 */
export const CreateScheduleRequest = new CreateScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetScheduleRequest$Type extends MessageType<GetScheduleRequest> {
    constructor() {
        super("schedule.GetScheduleRequest", [
            { no: 1, name: "schedule_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetScheduleRequest>): GetScheduleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scheduleId = "";
        if (value !== undefined)
            reflectionMergePartial<GetScheduleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetScheduleRequest): GetScheduleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string schedule_id */ 1:
                    message.scheduleId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetScheduleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string schedule_id = 1; */
        if (message.scheduleId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scheduleId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.GetScheduleRequest
 */
export const GetScheduleRequest = new GetScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScheduleRequest$Type extends MessageType<ListScheduleRequest> {
    constructor() {
        super("schedule.ListScheduleRequest", [
            { no: 1, name: "schedule_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListScheduleRequest>): ListScheduleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scheduleIds = [];
        if (value !== undefined)
            reflectionMergePartial<ListScheduleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListScheduleRequest): ListScheduleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string schedule_ids */ 1:
                    message.scheduleIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListScheduleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string schedule_ids = 1; */
        for (let i = 0; i < message.scheduleIds.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.scheduleIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.ListScheduleRequest
 */
export const ListScheduleRequest = new ListScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListScheduleResponse$Type extends MessageType<ListScheduleResponse> {
    constructor() {
        super("schedule.ListScheduleResponse", [
            { no: 1, name: "schedules", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Schedule }
        ]);
    }
    create(value?: PartialMessage<ListScheduleResponse>): ListScheduleResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.schedules = [];
        if (value !== undefined)
            reflectionMergePartial<ListScheduleResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListScheduleResponse): ListScheduleResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated schedule.Schedule schedules */ 1:
                    message.schedules.push(Schedule.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListScheduleResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated schedule.Schedule schedules = 1; */
        for (let i = 0; i < message.schedules.length; i++)
            Schedule.internalBinaryWrite(message.schedules[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.ListScheduleResponse
 */
export const ListScheduleResponse = new ListScheduleResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateScheduleRequest$Type extends MessageType<UpdateScheduleRequest> {
    constructor() {
        super("schedule.UpdateScheduleRequest", []);
    }
    create(value?: PartialMessage<UpdateScheduleRequest>): UpdateScheduleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateScheduleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateScheduleRequest): UpdateScheduleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateScheduleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.UpdateScheduleRequest
 */
export const UpdateScheduleRequest = new UpdateScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteScheduleRequest$Type extends MessageType<DeleteScheduleRequest> {
    constructor() {
        super("schedule.DeleteScheduleRequest", [
            { no: 1, name: "schedule_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteScheduleRequest>): DeleteScheduleRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.scheduleId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteScheduleRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteScheduleRequest): DeleteScheduleRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string schedule_id */ 1:
                    message.scheduleId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteScheduleRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string schedule_id = 1; */
        if (message.scheduleId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.scheduleId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.DeleteScheduleRequest
 */
export const DeleteScheduleRequest = new DeleteScheduleRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Schedule$Type extends MessageType<Schedule> {
    constructor() {
        super("schedule.Schedule", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "departament_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "day_of_week", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "hour", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "minute", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "video_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "create_at", kind: "message", T: () => Timestamp },
            { no: 8, name: "update_at", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<Schedule>): Schedule {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.departamentId = "";
        message.dayOfWeek = 0;
        message.hour = 0;
        message.minute = 0;
        message.videoId = "";
        if (value !== undefined)
            reflectionMergePartial<Schedule>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Schedule): Schedule {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string departament_id */ 2:
                    message.departamentId = reader.string();
                    break;
                case /* int32 day_of_week */ 3:
                    message.dayOfWeek = reader.int32();
                    break;
                case /* int32 hour */ 4:
                    message.hour = reader.int32();
                    break;
                case /* int32 minute */ 5:
                    message.minute = reader.int32();
                    break;
                case /* string video_id */ 6:
                    message.videoId = reader.string();
                    break;
                case /* google.protobuf.Timestamp create_at */ 7:
                    message.createAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.createAt);
                    break;
                case /* google.protobuf.Timestamp update_at */ 8:
                    message.updateAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updateAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Schedule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string departament_id = 2; */
        if (message.departamentId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.departamentId);
        /* int32 day_of_week = 3; */
        if (message.dayOfWeek !== 0)
            writer.tag(3, WireType.Varint).int32(message.dayOfWeek);
        /* int32 hour = 4; */
        if (message.hour !== 0)
            writer.tag(4, WireType.Varint).int32(message.hour);
        /* int32 minute = 5; */
        if (message.minute !== 0)
            writer.tag(5, WireType.Varint).int32(message.minute);
        /* string video_id = 6; */
        if (message.videoId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.videoId);
        /* google.protobuf.Timestamp create_at = 7; */
        if (message.createAt)
            Timestamp.internalBinaryWrite(message.createAt, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp update_at = 8; */
        if (message.updateAt)
            Timestamp.internalBinaryWrite(message.updateAt, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message schedule.Schedule
 */
export const Schedule = new Schedule$Type();
/**
 * @generated ServiceType for protobuf service schedule.ScheduleService
 */
export const ScheduleService = new ServiceType("schedule.ScheduleService", [
    { name: "CreateSchedule", options: {}, I: CreateScheduleRequest, O: Schedule },
    { name: "GetSchedule", options: {}, I: GetScheduleRequest, O: Schedule },
    { name: "ListSchedule", options: {}, I: ListScheduleRequest, O: ListScheduleResponse },
    { name: "UpdateSchedule", options: {}, I: UpdateScheduleRequest, O: Schedule },
    { name: "DeleteSchedule", options: {}, I: DeleteScheduleRequest, O: Empty }
]);
