/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/schedule/schedule.proto" (package "schedule", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ScheduleService } from "./schedule";
import type { Empty } from "../../google/protobuf/empty";
import type { DeleteScheduleRequest } from "./schedule";
import type { UpdateScheduleRequest } from "./schedule";
import type { ListScheduleResponse } from "./schedule";
import type { ListScheduleRequest } from "./schedule";
import type { GetScheduleRequest } from "./schedule";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Schedule } from "./schedule";
import type { CreateScheduleRequest } from "./schedule";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис для управления расписанием.
 *
 * @generated from protobuf service schedule.ScheduleService
 */
export interface IScheduleServiceClient {
    /**
     * Создает новое расписание.
     *
     * @generated from protobuf rpc: CreateSchedule(schedule.CreateScheduleRequest) returns (schedule.Schedule);
     */
    createSchedule(input: CreateScheduleRequest, options?: RpcOptions): UnaryCall<CreateScheduleRequest, Schedule>;
    /**
     * Получает расписание.
     *
     * @generated from protobuf rpc: GetSchedule(schedule.GetScheduleRequest) returns (schedule.Schedule);
     */
    getSchedule(input: GetScheduleRequest, options?: RpcOptions): UnaryCall<GetScheduleRequest, Schedule>;
    /**
     * Получает список расписание.
     *
     * @generated from protobuf rpc: ListSchedule(schedule.ListScheduleRequest) returns (schedule.ListScheduleResponse);
     */
    listSchedule(input: ListScheduleRequest, options?: RpcOptions): UnaryCall<ListScheduleRequest, ListScheduleResponse>;
    /**
     * Обновляет расписание.
     *
     * @generated from protobuf rpc: UpdateSchedule(schedule.UpdateScheduleRequest) returns (schedule.Schedule);
     */
    updateSchedule(input: UpdateScheduleRequest, options?: RpcOptions): UnaryCall<UpdateScheduleRequest, Schedule>;
    /**
     * Удаляет расписание.
     *
     * @generated from protobuf rpc: DeleteSchedule(schedule.DeleteScheduleRequest) returns (google.protobuf.Empty);
     */
    deleteSchedule(input: DeleteScheduleRequest, options?: RpcOptions): UnaryCall<DeleteScheduleRequest, Empty>;
}
/**
 * Сервис для управления расписанием.
 *
 * @generated from protobuf service schedule.ScheduleService
 */
export class ScheduleServiceClient implements IScheduleServiceClient, ServiceInfo {
    typeName = ScheduleService.typeName;
    methods = ScheduleService.methods;
    options = ScheduleService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Создает новое расписание.
     *
     * @generated from protobuf rpc: CreateSchedule(schedule.CreateScheduleRequest) returns (schedule.Schedule);
     */
    createSchedule(input: CreateScheduleRequest, options?: RpcOptions): UnaryCall<CreateScheduleRequest, Schedule> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateScheduleRequest, Schedule>("unary", this._transport, method, opt, input);
    }
    /**
     * Получает расписание.
     *
     * @generated from protobuf rpc: GetSchedule(schedule.GetScheduleRequest) returns (schedule.Schedule);
     */
    getSchedule(input: GetScheduleRequest, options?: RpcOptions): UnaryCall<GetScheduleRequest, Schedule> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetScheduleRequest, Schedule>("unary", this._transport, method, opt, input);
    }
    /**
     * Получает список расписание.
     *
     * @generated from protobuf rpc: ListSchedule(schedule.ListScheduleRequest) returns (schedule.ListScheduleResponse);
     */
    listSchedule(input: ListScheduleRequest, options?: RpcOptions): UnaryCall<ListScheduleRequest, ListScheduleResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListScheduleRequest, ListScheduleResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Обновляет расписание.
     *
     * @generated from protobuf rpc: UpdateSchedule(schedule.UpdateScheduleRequest) returns (schedule.Schedule);
     */
    updateSchedule(input: UpdateScheduleRequest, options?: RpcOptions): UnaryCall<UpdateScheduleRequest, Schedule> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateScheduleRequest, Schedule>("unary", this._transport, method, opt, input);
    }
    /**
     * Удаляет расписание.
     *
     * @generated from protobuf rpc: DeleteSchedule(schedule.DeleteScheduleRequest) returns (google.protobuf.Empty);
     */
    deleteSchedule(input: DeleteScheduleRequest, options?: RpcOptions): UnaryCall<DeleteScheduleRequest, Empty> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteScheduleRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
