/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: v1/auth/auth.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_auth_auth_pb from '../../v1/auth/auth_pb'; // proto import: "v1/auth/auth.proto"


export class AuthServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegister = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/Register',
    grpcWeb.MethodType.UNARY,
    v1_auth_auth_pb.AuthRequest,
    v1_auth_auth_pb.RegisterResponse,
    (request: v1_auth_auth_pb.AuthRequest) => {
      return request.serializeBinary();
    },
    v1_auth_auth_pb.RegisterResponse.deserializeBinary
  );

  register(
    request: v1_auth_auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_auth_pb.RegisterResponse>;

  register(
    request: v1_auth_auth_pb.AuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.RegisterResponse) => void): grpcWeb.ClientReadableStream<v1_auth_auth_pb.RegisterResponse>;

  register(
    request: v1_auth_auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.RegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/Register',
        request,
        metadata || {},
        this.methodDescriptorRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/Register',
    request,
    metadata || {},
    this.methodDescriptorRegister);
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/Login',
    grpcWeb.MethodType.UNARY,
    v1_auth_auth_pb.AuthRequest,
    v1_auth_auth_pb.LoginResponse,
    (request: v1_auth_auth_pb.AuthRequest) => {
      return request.serializeBinary();
    },
    v1_auth_auth_pb.LoginResponse.deserializeBinary
  );

  login(
    request: v1_auth_auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_auth_pb.LoginResponse>;

  login(
    request: v1_auth_auth_pb.AuthRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.LoginResponse) => void): grpcWeb.ClientReadableStream<v1_auth_auth_pb.LoginResponse>;

  login(
    request: v1_auth_auth_pb.AuthRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.LoginResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorResetPassword = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/ResetPassword',
    grpcWeb.MethodType.UNARY,
    v1_auth_auth_pb.ResetPasswordRequest,
    v1_auth_auth_pb.ResetPasswordResponse,
    (request: v1_auth_auth_pb.ResetPasswordRequest) => {
      return request.serializeBinary();
    },
    v1_auth_auth_pb.ResetPasswordResponse.deserializeBinary
  );

  resetPassword(
    request: v1_auth_auth_pb.ResetPasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_auth_pb.ResetPasswordResponse>;

  resetPassword(
    request: v1_auth_auth_pb.ResetPasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.ResetPasswordResponse) => void): grpcWeb.ClientReadableStream<v1_auth_auth_pb.ResetPasswordResponse>;

  resetPassword(
    request: v1_auth_auth_pb.ResetPasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.ResetPasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/ResetPassword',
        request,
        metadata || {},
        this.methodDescriptorResetPassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/ResetPassword',
    request,
    metadata || {},
    this.methodDescriptorResetPassword);
  }

  methodDescriptorChangePassword = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/ChangePassword',
    grpcWeb.MethodType.UNARY,
    v1_auth_auth_pb.ChangePasswordRequest,
    v1_auth_auth_pb.ChangePasswordResponse,
    (request: v1_auth_auth_pb.ChangePasswordRequest) => {
      return request.serializeBinary();
    },
    v1_auth_auth_pb.ChangePasswordResponse.deserializeBinary
  );

  changePassword(
    request: v1_auth_auth_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_auth_pb.ChangePasswordResponse>;

  changePassword(
    request: v1_auth_auth_pb.ChangePasswordRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.ChangePasswordResponse) => void): grpcWeb.ClientReadableStream<v1_auth_auth_pb.ChangePasswordResponse>;

  changePassword(
    request: v1_auth_auth_pb.ChangePasswordRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.ChangePasswordResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/ChangePassword',
        request,
        metadata || {},
        this.methodDescriptorChangePassword,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/ChangePassword',
    request,
    metadata || {},
    this.methodDescriptorChangePassword);
  }

  methodDescriptorVerifyRegister = new grpcWeb.MethodDescriptor(
    '/auth.AuthService/VerifyRegister',
    grpcWeb.MethodType.UNARY,
    v1_auth_auth_pb.VerifyRegisterRequest,
    v1_auth_auth_pb.VerifyRegisterResponse,
    (request: v1_auth_auth_pb.VerifyRegisterRequest) => {
      return request.serializeBinary();
    },
    v1_auth_auth_pb.VerifyRegisterResponse.deserializeBinary
  );

  verifyRegister(
    request: v1_auth_auth_pb.VerifyRegisterRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_auth_auth_pb.VerifyRegisterResponse>;

  verifyRegister(
    request: v1_auth_auth_pb.VerifyRegisterRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.VerifyRegisterResponse) => void): grpcWeb.ClientReadableStream<v1_auth_auth_pb.VerifyRegisterResponse>;

  verifyRegister(
    request: v1_auth_auth_pb.VerifyRegisterRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_auth_auth_pb.VerifyRegisterResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.AuthService/VerifyRegister',
        request,
        metadata || {},
        this.methodDescriptorVerifyRegister,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.AuthService/VerifyRegister',
    request,
    metadata || {},
    this.methodDescriptorVerifyRegister);
  }

}

