/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/auth/auth.proto" (package "auth", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { VerifyRegisterResponse } from "./auth";
import type { VerifyRegisterRequest } from "./auth";
import type { ChangePasswordResponse } from "./auth";
import type { ChangePasswordRequest } from "./auth";
import type { ResetPasswordResponse } from "./auth";
import type { ResetPasswordRequest } from "./auth";
import type { LoginResponse } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RegisterResponse } from "./auth";
import type { AuthRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис для аутентификации и регистрации пользователей.
 *
 * @generated from protobuf service auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * Регистрирует нового пользователя.
     *
     * @generated from protobuf rpc: Register(auth.AuthRequest) returns (auth.RegisterResponse);
     */
    register(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, RegisterResponse>;
    /**
     * Аутентифицирует пользователя.
     *
     * @generated from protobuf rpc: Login(auth.AuthRequest) returns (auth.LoginResponse);
     */
    login(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, LoginResponse>;
    /**
     * Сбрасывает пароль пользователя.
     *
     * @generated from protobuf rpc: ResetPassword(auth.ResetPasswordRequest) returns (auth.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse>;
    /**
     * подтверждает сброс пароля пользователя по токену.
     *
     * @generated from protobuf rpc: ChangePassword(auth.ChangePasswordRequest) returns (auth.ChangePasswordResponse);
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse>;
    /**
     * Подтверждает регистрацию пользователя по токену.
     * Токен отправляется на почту пользователя.
     *
     * @generated from protobuf rpc: VerifyRegister(auth.VerifyRegisterRequest) returns (auth.VerifyRegisterResponse);
     */
    verifyRegister(input: VerifyRegisterRequest, options?: RpcOptions): UnaryCall<VerifyRegisterRequest, VerifyRegisterResponse>;
}
/**
 * Сервис для аутентификации и регистрации пользователей.
 *
 * @generated from protobuf service auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Регистрирует нового пользователя.
     *
     * @generated from protobuf rpc: Register(auth.AuthRequest) returns (auth.RegisterResponse);
     */
    register(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, RegisterResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthRequest, RegisterResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Аутентифицирует пользователя.
     *
     * @generated from protobuf rpc: Login(auth.AuthRequest) returns (auth.LoginResponse);
     */
    login(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, LoginResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Сбрасывает пароль пользователя.
     *
     * @generated from protobuf rpc: ResetPassword(auth.ResetPasswordRequest) returns (auth.ResetPasswordResponse);
     */
    resetPassword(input: ResetPasswordRequest, options?: RpcOptions): UnaryCall<ResetPasswordRequest, ResetPasswordResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetPasswordRequest, ResetPasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * подтверждает сброс пароля пользователя по токену.
     *
     * @generated from protobuf rpc: ChangePassword(auth.ChangePasswordRequest) returns (auth.ChangePasswordResponse);
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangePasswordRequest, ChangePasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Подтверждает регистрацию пользователя по токену.
     * Токен отправляется на почту пользователя.
     *
     * @generated from protobuf rpc: VerifyRegister(auth.VerifyRegisterRequest) returns (auth.VerifyRegisterResponse);
     */
    verifyRegister(input: VerifyRegisterRequest, options?: RpcOptions): UnaryCall<VerifyRegisterRequest, VerifyRegisterResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyRegisterRequest, VerifyRegisterResponse>("unary", this._transport, method, opt, input);
    }
}
