syntax="proto3";

package schedule;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "google/api/field_behavior.proto";

// Сервис для управления расписанием.
service ScheduleService {

    // Создает новое расписание.
    rpc CreateSchedules(CreateSchedulesRequest) returns (CreateSchedulesResponse);

    // Получает расписание.
    rpc GetSchedule(GetScheduleRequest) returns (Schedule);

    // Получает список расписание.
    rpc ListSchedule(ListScheduleRequest) returns (ListScheduleResponse);

    // Обновляет расписание.
    rpc UpdateSchedule(UpdateScheduleRequest) returns (Schedule);

    // Удаляет расписание.
    rpc DeleteSchedule(DeleteScheduleRequest) returns (google.protobuf.Empty);
}

// Запрос на создание расписания.
message CreateSchedulesRequest {
    // Расписания, которые необходимо создать.
    repeated Schedule schedules = 1;
}

// Ответ на запрос создания расписания.
// Возвращает список сохраненных в БД расписаний.
message CreateSchedulesResponse {
    // Список сохраненных расписаний.
    repeated Schedule schedules = 1;
}

//Запрос на получение расписания.
message GetScheduleRequest {
    // ID расписания, которое необходимо получить.
    string schedule_id = 1;
}

// Запрос на получение списка расписаний.
message ListScheduleRequest {
    // ID расписания, которое необходимо получить.
    repeated string schedule_ids = 1;
}

// Ответ на запрос списка расписаний.
message ListScheduleResponse {
    // Список расписаний.
    repeated Schedule schedules = 1;
}

// Запрос на обновление расписания.
message UpdateScheduleRequest {
    // Нужно согласовать какие поля расписания можно менять.
}

// Запрос на удаление расписания.
message DeleteScheduleRequest {
    // ID расписания, которое необходимо удалить.
    string schedule_id = 1;
}

// Струкутура расписания.
message Schedule {
    // ID расписания.
    int64 id = 1 [(google.api.field_behavior) = OUTPUT_ONLY];

    // Cron-выражение - представления времени запуска. (Формат crontab)
    //
    // * * * * * 
    // | | | | |
    // | | | | +----- Дни недели (диапазон: 1-7)
    // | | | +------- Месяцы     (диапазон: 1-12)
    // | | +--------- Дни месяца (диапазон: 1-31)
    // | +----------- Часы       (диапазон: 0-23)
    // +------------- Минуты     (диапазон: 0-59)
    //
    // Примеры: 
    // * * * * * (каждую минуту, каждого часа и каждого тд)
    // 30 * * * * (в 30 минут, каждого часа и каждого тд)
    // https://ru.wikipedia.org/wiki/Cron#crontab
    string cron_expression = 3;

    // Активно расписание или нет.
    bool is_active = 4;

    // ID видео, которое необходимо воспроизвести по расписанию.
    int64 video_id = 5;

    // ID админа, который создал расписание.
    int64 admin_id = 6 [(google.api.field_behavior) = OUTPUT_ONLY];

    // Время создания расписания.
    google.protobuf.Timestamp created_at = 7 [(google.api.field_behavior) = OUTPUT_ONLY];
}
    