env: "dev"
storage: "postgres://postgres:root@postgres:5432/health?sslmode=disable" # Если Go код будет выполняться из контейнера, то нужно @localhost:5436/health"
token_ttl: 1h # Срок жизни токена сервиса
auth_token_ttl: 15m # Срок жизни токена аутентификации
grpc:
  port: 9090
  timeout: 15s
smtp:
  email_sender: "mysenderdeveloper@gmail.com"
  email_password: "kdbw armw mmrh mlnp"
  username: "mysenderdeveloper"
  host: "smtp.gmail.com"
  port: 587