syntax="proto3";

package auth;
option go_package = "github.com/Enfariches/gym/protogen";

// Сервис для аутентификации и регистрации пользователей.
service AuthService {

    // Регистрирует нового пользователя.
    rpc Register(AuthRequest) returns (RegisterResponse);

    // Аутентифицирует пользователя.
    rpc Login(AuthRequest) returns (LoginResponse);

    // Сбрасывает пароль пользователя.
    rpc ResetPassword(ResetPasswordRequest) returns (ResetPasswordResponse);

    // подтверждает сброс пароля пользователя по токену.
    rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);

    // Подтверждает регистрацию пользователя по токену.
    // Токен отправляется на почту пользователя.
    rpc VerifyRegister(VerifyRegisterRequest) returns (VerifyRegisterResponse);
}

// Запрос на аутентификацию или регистрацию.
message AuthRequest {
    // Электронная почта пользователя.
    string email = 1;
    
    // Пароль пользователя.
    string password = 2;

    // Источник запроса (клиент или админка)
    AppSource source = 3;
}

// Запрос на сброс пароля пользователя.
message ResetPasswordRequest {
    // Электронная почта пользователя.
    string email = 1;

    // Источник запроса (клиент или админка)
    AppSource source = 2;
}

// Ответ на сброс пароля.
message ResetPasswordResponse {
    // Токен для сброса пароля.
    string reset_token = 1;
}

// Запрос на подтверждение сброса пароля.
message ChangePasswordRequest {
    // Токен для сброса пароля.
    string reset_token = 1;

    // Новый пароль пользователя.
    string new_password = 2;
}

message ChangePasswordResponse {
    // Возвращает OK, если сброс пароля прошёл успешно.
    // Возвращает ERROR, если сброс пароля не прошёл.
}

message VerifyRegisterRequest {
    // JWT-токен для подтверждения регистрации. Включает в себя email и хэш пароля.
    string auth_token = 1;
}

// Ответ на аутентификацию.
message LoginResponse {
    //JWT-токен, используемый для последующих запросов.
    string token = 1;
}

// Ответ на регистрацию пользователя.
message RegisterResponse {
    // JWT-токен для подтверждения регистрации. Включает в себя email и хэш пароля.
    // Так же отправляется на почту линк с потверждением.
    string auth_token = 1;
}

message VerifyRegisterResponse {
    // Возвращает OK, если регистрация прошла успешно.
    // Возвращает ERROR, если регистрация не прошла.
}

// Тип приложения, от которого пришёл запрос
enum AppSource {
    // Неизвестный источник
    APP_SOURCE_UNSPECIFIED = 0; 

    // Клиентское приложение
    EMPLOYEE = 1;
    
    // Админ-панель
    ADMIN = 2;      
}
    