syntax="proto3";

package auth;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/empty.proto";

// Сервис для аутентификации и регистрации пользователей.
service AuthService {

    // Регистрирует нового пользователя.
    rpc Register(AuthRequest) returns (RegisterResponse);

    // Аутентифицирует пользователя.
    rpc Login(AuthRequest) returns (LoginResponse);

    // Обновляет пароль пользователя.
    rpc ChangePassword(ChangePasswordRequest) returns (ChangePasswordResponse);

    // Подтверждает смену пароля пользователя по токену.
    rpc VerifyChangePassword(VerifyChangePasswordRequest) returns (google.protobuf.Empty);

    // Подтверждает регистрацию пользователя по токену.
    // Токен отправляется на почту пользователя.
    rpc VerifyRegister(VerifyRegisterRequest) returns (google.protobuf.Empty);
}

// Запрос на аутентификацию или регистрацию.
message AuthRequest {
    // Электронная почта пользователя.
    string email = 1;

    // Пароль пользователя.
    string password = 2;

    // Источник запроса (клиент или админка)
    AppSource source = 3;
}

// Запрос на смену пароля пользователя.
message ChangePasswordRequest {
    // Электронная почта пользователя.
    string email = 1;

    // Источник запроса (клиент или админка)
    AppSource source = 2;
}

// Ответ на смену пароля.
message ChangePasswordResponse {
    // Токен для сброса пароля.
    string reset_token = 1;
}

// Запрос на подтверждение смены пароля.
message VerifyChangePasswordRequest {
    // Токен для смены пароля.
    string reset_token = 1;

    // Новый пароль пользователя.
    string new_password = 2;
}

message VerifyRegisterRequest {
    // JWT-токен для подтверждения регистрации. Включает в себя email и хэш пароля.
    string auth_token = 1;
}

// Ответ на аутентификацию.
message LoginResponse {
    //JWT-токен, используемый для последующих запросов.
    string token = 1;
}

// Ответ на регистрацию пользователя.
message RegisterResponse {
    // JWT-токен для подтверждения регистрации. Включает в себя email и хэш пароля.
    // Так же отправляется на почту линк с потверждением.
    string auth_token = 1;
}

// Тип приложения, от которого пришёл запрос
enum AppSource {
    // Неизвестный источник
    APP_SOURCE_UNSPECIFIED = 0;

    // Клиентское приложение
    EMPLOYEE = 1;

    // Админ-панель
    ADMIN = 2;
}
