syntax="proto3";

package admin;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/field_mask.proto";

// Сервис для управления администраторами.
service AdminService {
    // Получает администратора.
    rpc GetAdmin (GetAdminRequest) returns (Admin);

    // Обновляет администратора.
    rpc UpdateAdmin (UpdateAdminRequest) returns (Admin);
}

// Запрос на получение администратора.
message GetAdminRequest {
    // ID администратора.
    int64 admin_id = 1;
}

// Запрос на обновление администратора.
message UpdateAdminRequest {
    // Администратор, который будет обновлен.
    Admin admin = 1;

    // Маска полей, которые будут обновлены.
    google.protobuf.FieldMask field_mask = 2;
}


// Структура администратора.
message Admin {
    // ID администратора.
    int64 id = 1;

    // Имя администратора.
	string name = 2;

    // Фамилия администратора.
	string surname = 3;

    // Электронная почта администратора.
	string email = 4;

    // Отдел за котором закреплен администратор.
	string departament = 5;
}