syntax="proto3";

package admin;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/empty.proto";

// Сервис для управления администраторами.
service AdminService {

    // Получает администратора.
    rpc GetAdmin (GetAdminRequest) returns (Admin);

    // Обновляет администратора.
    rpc UpdateAdmin (UpdateAdminRequest) returns (Admin);

    // Удаляет администратора.
    rpc DeleteAdmin (DeleteAdminRequest) returns (google.protobuf.Empty);

    // Проверяет, является ли пользователь администратором.
    rpc IsAdmin (IsAdminRequest) returns (IsAdminResponse);
}

// Запрос на получение администратора.
message GetAdminRequest {
    string admin_id = 1;
}

// Запрос на обновление администратора.
message UpdateAdminRequest {
    // Нужно согласовать какие поля расписания можно менять.
}

// Запрос на проверку администратора.
message IsAdminRequest {
    string admin_id = 1;
}

// Запрос на удаление администратора.
message DeleteAdminRequest {
    string admin_id = 1;
}

// Ответ на запрос проверки администратора.
message IsAdminResponse {
    // Флаг, является ли пользователь администратором.
    bool IsAdmin = 1;
}

// Структура администратора.
message Admin {
    // ID администратора.
    string id = 1;

    // Имя администратора.
	string name = 2;

    // Фамилия администратора.
	string surname = 3;

    // Электронная почта администратора.
	string email = 4;

    // Отдел за котором закреплен администратор.
	string departament = 5;
}