syntax="proto3";

package employee;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";

// Сервис для управления пользователями.
service EmployeeService {
    // Получает пользователя.
    rpc GetEmployee (google.protobuf.Empty) returns (Employee);

    // Обновляет пользователя.
    rpc UpdateEmployee (UpdateEmployeeRequest) returns (Employee);

    // Удаляет пользователя.
    rpc DeleteEmployee (google.protobuf.Empty) returns (google.protobuf.Empty);

    // Список всех существующих отделов
    rpc ListDepartments (google.protobuf.Empty) returns (ListDepartmentsResponse);
}

// Запрос на обновление пользователя.
message UpdateEmployeeRequest {
    // Cотрудник, который будет обновлен.
    Employee employee = 1;

    // Маска полей, которые будут обновлены.
    google.protobuf.FieldMask field_mask = 2;
}

// Ответ на запрос списка отделов
message ListDepartmentsResponse {
    // Список отделов
    repeated Department departments = 1;
}

// Структура пользователя.
message Employee {
    // ID пользователя.
    int64 id = 1;

    // Имя пользователя.
    string name = 2;

    // Отчество пользователя.
    string second_name = 3;

    // Фамилия пользователя.
    string surname = 4;

    // Электронная почта пользователя.
    string email = 5;

    // Возраст пользователя.
    int64 age = 6;

    // Пол пользователя.
    // False - мужчина; True - женщина;
    bool sex = 7;

    // Номер телефона пользователя.
    string phone = 8;

    // Отдел пользователя.
    string department = 9;

    // Должность пользователя.
    string post = 10;
}

message Department {
    // ID отдела.
    int64 id = 1;

    // Название отдела.
    string name = 2;
}
