syntax="proto3";

package employee;
option go_package = "github.com/Enfariches/gym/protogen";

import "google/protobuf/empty.proto";

// Сервис для управления пользователями.
service EmployeeService {
    // Получает пользователя.
    rpc GetEmployee (GetEmployeeRequest) returns (Employee);

    // Обновляет пользователя.
    rpc UpdateEmployee (UpdateEmployeeRequest) returns (Employee);

    // Удаляет пользователя.
    rpc DeleteEmployee (DeleteEmployeeRequest) returns (google.protobuf.Empty);
}

// Запрос на получение пользователя.
message GetEmployeeRequest {
    // ID пользователя.
    int64 employee_id = 1;
}

// Запрос на обновление пользователя.
message UpdateEmployeeRequest {
    // Нужно согласовать какие поля расписания можно менять.
}

// Запрос на удаление пользователя.
message DeleteEmployeeRequest {
    // ID пользователя.
    int64 employee_id = 1;
}

// Структура пользователя.
message Employee {
    // ID пользователя.
    int64 id = 1;

    // Имя пользователя.
    string name = 2;

    // Отчество пользователя.
    string secondName = 3;

    // Фамилия пользователя.
    string surname = 4;

    // Электронная почта пользователя.
    string email = 5;

    // Возраст пользователя.
    uint32 age = 6;

    // Пол пользователя.
    bool sex = 7;

    // Номер телефона пользователя.
    string number = 8;

    // Отдел пользователя.
    string department = 9;

    // Должность пользователя.
    string post = 10;
}