/**
 * @fileoverview gRPC-Web generated client stub for admin
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: v1/user/admin.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_user_admin_pb from '../../v1/user/admin_pb'; // proto import: "v1/user/admin.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class AdminServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAdmin = new grpcWeb.MethodDescriptor(
    '/admin.AdminService/GetAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_admin_pb.GetAdminRequest,
    v1_user_admin_pb.Admin,
    (request: v1_user_admin_pb.GetAdminRequest) => {
      return request.serializeBinary();
    },
    v1_user_admin_pb.Admin.deserializeBinary
  );

  getAdmin(
    request: v1_user_admin_pb.GetAdminRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_user_admin_pb.Admin>;

  getAdmin(
    request: v1_user_admin_pb.GetAdminRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.Admin) => void): grpcWeb.ClientReadableStream<v1_user_admin_pb.Admin>;

  getAdmin(
    request: v1_user_admin_pb.GetAdminRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.Admin) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/admin.AdminService/GetAdmin',
        request,
        metadata || {},
        this.methodDescriptorGetAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/admin.AdminService/GetAdmin',
    request,
    metadata || {},
    this.methodDescriptorGetAdmin);
  }

  methodDescriptorUpdateAdmin = new grpcWeb.MethodDescriptor(
    '/admin.AdminService/UpdateAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_admin_pb.UpdateAdminRequest,
    v1_user_admin_pb.Admin,
    (request: v1_user_admin_pb.UpdateAdminRequest) => {
      return request.serializeBinary();
    },
    v1_user_admin_pb.Admin.deserializeBinary
  );

  updateAdmin(
    request: v1_user_admin_pb.UpdateAdminRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_user_admin_pb.Admin>;

  updateAdmin(
    request: v1_user_admin_pb.UpdateAdminRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.Admin) => void): grpcWeb.ClientReadableStream<v1_user_admin_pb.Admin>;

  updateAdmin(
    request: v1_user_admin_pb.UpdateAdminRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.Admin) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/admin.AdminService/UpdateAdmin',
        request,
        metadata || {},
        this.methodDescriptorUpdateAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/admin.AdminService/UpdateAdmin',
    request,
    metadata || {},
    this.methodDescriptorUpdateAdmin);
  }

  methodDescriptorDeleteAdmin = new grpcWeb.MethodDescriptor(
    '/admin.AdminService/DeleteAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_admin_pb.DeleteAdminRequest,
    google_protobuf_empty_pb.Empty,
    (request: v1_user_admin_pb.DeleteAdminRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteAdmin(
    request: v1_user_admin_pb.DeleteAdminRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteAdmin(
    request: v1_user_admin_pb.DeleteAdminRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteAdmin(
    request: v1_user_admin_pb.DeleteAdminRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/admin.AdminService/DeleteAdmin',
        request,
        metadata || {},
        this.methodDescriptorDeleteAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/admin.AdminService/DeleteAdmin',
    request,
    metadata || {},
    this.methodDescriptorDeleteAdmin);
  }

  methodDescriptorIsAdmin = new grpcWeb.MethodDescriptor(
    '/admin.AdminService/IsAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_admin_pb.IsAdminRequest,
    v1_user_admin_pb.IsAdminResponse,
    (request: v1_user_admin_pb.IsAdminRequest) => {
      return request.serializeBinary();
    },
    v1_user_admin_pb.IsAdminResponse.deserializeBinary
  );

  isAdmin(
    request: v1_user_admin_pb.IsAdminRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_user_admin_pb.IsAdminResponse>;

  isAdmin(
    request: v1_user_admin_pb.IsAdminRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.IsAdminResponse) => void): grpcWeb.ClientReadableStream<v1_user_admin_pb.IsAdminResponse>;

  isAdmin(
    request: v1_user_admin_pb.IsAdminRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_user_admin_pb.IsAdminResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/admin.AdminService/IsAdmin',
        request,
        metadata || {},
        this.methodDescriptorIsAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/admin.AdminService/IsAdmin',
    request,
    metadata || {},
    this.methodDescriptorIsAdmin);
  }

}

