/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/user/admin.proto" (package "admin", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Empty } from "../../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Запрос на получение администратора.
 *
 * @generated from protobuf message admin.GetAdminRequest
 */
export interface GetAdminRequest {
    /**
     * @generated from protobuf field: string admin_id = 1;
     */
    adminId: string;
}
/**
 * Запрос на обновление администратора.
 *
 * Нужно согласовать какие поля расписания можно менять.
 *
 * @generated from protobuf message admin.UpdateAdminRequest
 */
export interface UpdateAdminRequest {
}
/**
 * Запрос на проверку администратора.
 *
 * @generated from protobuf message admin.IsAdminRequest
 */
export interface IsAdminRequest {
    /**
     * @generated from protobuf field: string admin_id = 1;
     */
    adminId: string;
}
/**
 * Запрос на удаление администратора.
 *
 * @generated from protobuf message admin.DeleteAdminRequest
 */
export interface DeleteAdminRequest {
    /**
     * @generated from protobuf field: string admin_id = 1;
     */
    adminId: string;
}
/**
 * Ответ на запрос проверки администратора.
 *
 * @generated from protobuf message admin.IsAdminResponse
 */
export interface IsAdminResponse {
    /**
     * Флаг, является ли пользователь администратором.
     *
     * @generated from protobuf field: bool IsAdmin = 1 [json_name = "IsAdmin"];
     */
    isAdmin: boolean;
}
/**
 * Структура администратора.
 *
 * @generated from protobuf message admin.Admin
 */
export interface Admin {
    /**
     * ID администратора.
     *
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * Имя администратора.
     *
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * Фамилия администратора.
     *
     * @generated from protobuf field: string surname = 3;
     */
    surname: string;
    /**
     * Электронная почта администратора.
     *
     * @generated from protobuf field: string email = 4;
     */
    email: string;
    /**
     * Отдел за котором закреплен администратор.
     *
     * @generated from protobuf field: string departament = 5;
     */
    departament: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetAdminRequest$Type extends MessageType<GetAdminRequest> {
    constructor() {
        super("admin.GetAdminRequest", [
            { no: 1, name: "admin_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetAdminRequest>): GetAdminRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.adminId = "";
        if (value !== undefined)
            reflectionMergePartial<GetAdminRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAdminRequest): GetAdminRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string admin_id */ 1:
                    message.adminId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAdminRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string admin_id = 1; */
        if (message.adminId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.adminId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.GetAdminRequest
 */
export const GetAdminRequest = new GetAdminRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateAdminRequest$Type extends MessageType<UpdateAdminRequest> {
    constructor() {
        super("admin.UpdateAdminRequest", []);
    }
    create(value?: PartialMessage<UpdateAdminRequest>): UpdateAdminRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateAdminRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateAdminRequest): UpdateAdminRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateAdminRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.UpdateAdminRequest
 */
export const UpdateAdminRequest = new UpdateAdminRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IsAdminRequest$Type extends MessageType<IsAdminRequest> {
    constructor() {
        super("admin.IsAdminRequest", [
            { no: 1, name: "admin_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<IsAdminRequest>): IsAdminRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.adminId = "";
        if (value !== undefined)
            reflectionMergePartial<IsAdminRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsAdminRequest): IsAdminRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string admin_id */ 1:
                    message.adminId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsAdminRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string admin_id = 1; */
        if (message.adminId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.adminId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.IsAdminRequest
 */
export const IsAdminRequest = new IsAdminRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteAdminRequest$Type extends MessageType<DeleteAdminRequest> {
    constructor() {
        super("admin.DeleteAdminRequest", [
            { no: 1, name: "admin_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteAdminRequest>): DeleteAdminRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.adminId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteAdminRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteAdminRequest): DeleteAdminRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string admin_id */ 1:
                    message.adminId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteAdminRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string admin_id = 1; */
        if (message.adminId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.adminId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.DeleteAdminRequest
 */
export const DeleteAdminRequest = new DeleteAdminRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class IsAdminResponse$Type extends MessageType<IsAdminResponse> {
    constructor() {
        super("admin.IsAdminResponse", [
            { no: 1, name: "IsAdmin", kind: "scalar", jsonName: "IsAdmin", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<IsAdminResponse>): IsAdminResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isAdmin = false;
        if (value !== undefined)
            reflectionMergePartial<IsAdminResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IsAdminResponse): IsAdminResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool IsAdmin = 1 [json_name = "IsAdmin"];*/ 1:
                    message.isAdmin = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: IsAdminResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool IsAdmin = 1 [json_name = "IsAdmin"]; */
        if (message.isAdmin !== false)
            writer.tag(1, WireType.Varint).bool(message.isAdmin);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.IsAdminResponse
 */
export const IsAdminResponse = new IsAdminResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Admin$Type extends MessageType<Admin> {
    constructor() {
        super("admin.Admin", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "departament", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Admin>): Admin {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.surname = "";
        message.email = "";
        message.departament = "";
        if (value !== undefined)
            reflectionMergePartial<Admin>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Admin): Admin {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string surname */ 3:
                    message.surname = reader.string();
                    break;
                case /* string email */ 4:
                    message.email = reader.string();
                    break;
                case /* string departament */ 5:
                    message.departament = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Admin, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string surname = 3; */
        if (message.surname !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.surname);
        /* string email = 4; */
        if (message.email !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.email);
        /* string departament = 5; */
        if (message.departament !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.departament);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message admin.Admin
 */
export const Admin = new Admin$Type();
/**
 * @generated ServiceType for protobuf service admin.AdminService
 */
export const AdminService = new ServiceType("admin.AdminService", [
    { name: "GetAdmin", options: {}, I: GetAdminRequest, O: Admin },
    { name: "UpdateAdmin", options: {}, I: UpdateAdminRequest, O: Admin },
    { name: "DeleteAdmin", options: {}, I: DeleteAdminRequest, O: Empty },
    { name: "IsAdmin", options: {}, I: IsAdminRequest, O: IsAdminResponse }
]);
