/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.30.2
 * source: v1/user/admin.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\..\\google\\protobuf\\empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace admin {
    export class GetAdminRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            admin_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("admin_id" in data && data.admin_id != undefined) {
                    this.admin_id = data.admin_id;
                }
            }
        }
        get admin_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set admin_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            admin_id?: string;
        }): GetAdminRequest {
            const message = new GetAdminRequest({});
            if (data.admin_id != null) {
                message.admin_id = data.admin_id;
            }
            return message;
        }
        toObject() {
            const data: {
                admin_id?: string;
            } = {};
            if (this.admin_id != null) {
                data.admin_id = this.admin_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.admin_id.length)
                writer.writeString(1, this.admin_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetAdminRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetAdminRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.admin_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetAdminRequest {
            return GetAdminRequest.deserialize(bytes);
        }
    }
    export class UpdateAdminRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): UpdateAdminRequest {
            const message = new UpdateAdminRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateAdminRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateAdminRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UpdateAdminRequest {
            return UpdateAdminRequest.deserialize(bytes);
        }
    }
    export class IsAdminRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            admin_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("admin_id" in data && data.admin_id != undefined) {
                    this.admin_id = data.admin_id;
                }
            }
        }
        get admin_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set admin_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            admin_id?: string;
        }): IsAdminRequest {
            const message = new IsAdminRequest({});
            if (data.admin_id != null) {
                message.admin_id = data.admin_id;
            }
            return message;
        }
        toObject() {
            const data: {
                admin_id?: string;
            } = {};
            if (this.admin_id != null) {
                data.admin_id = this.admin_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.admin_id.length)
                writer.writeString(1, this.admin_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IsAdminRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new IsAdminRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.admin_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): IsAdminRequest {
            return IsAdminRequest.deserialize(bytes);
        }
    }
    export class DeleteAdminRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            admin_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("admin_id" in data && data.admin_id != undefined) {
                    this.admin_id = data.admin_id;
                }
            }
        }
        get admin_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set admin_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            admin_id?: string;
        }): DeleteAdminRequest {
            const message = new DeleteAdminRequest({});
            if (data.admin_id != null) {
                message.admin_id = data.admin_id;
            }
            return message;
        }
        toObject() {
            const data: {
                admin_id?: string;
            } = {};
            if (this.admin_id != null) {
                data.admin_id = this.admin_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.admin_id.length)
                writer.writeString(1, this.admin_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteAdminRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteAdminRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.admin_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteAdminRequest {
            return DeleteAdminRequest.deserialize(bytes);
        }
    }
    export class IsAdminResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            IsAdmin?: boolean;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("IsAdmin" in data && data.IsAdmin != undefined) {
                    this.IsAdmin = data.IsAdmin;
                }
            }
        }
        get IsAdmin() {
            return pb_1.Message.getFieldWithDefault(this, 1, false) as boolean;
        }
        set IsAdmin(value: boolean) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            IsAdmin?: boolean;
        }): IsAdminResponse {
            const message = new IsAdminResponse({});
            if (data.IsAdmin != null) {
                message.IsAdmin = data.IsAdmin;
            }
            return message;
        }
        toObject() {
            const data: {
                IsAdmin?: boolean;
            } = {};
            if (this.IsAdmin != null) {
                data.IsAdmin = this.IsAdmin;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.IsAdmin != false)
                writer.writeBool(1, this.IsAdmin);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): IsAdminResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new IsAdminResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.IsAdmin = reader.readBool();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): IsAdminResponse {
            return IsAdminResponse.deserialize(bytes);
        }
    }
    export class Admin extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            name?: string;
            surname?: string;
            email?: string;
            departament?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("surname" in data && data.surname != undefined) {
                    this.surname = data.surname;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("departament" in data && data.departament != undefined) {
                    this.departament = data.departament;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get surname() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set surname(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get departament() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set departament(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            id?: string;
            name?: string;
            surname?: string;
            email?: string;
            departament?: string;
        }): Admin {
            const message = new Admin({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.surname != null) {
                message.surname = data.surname;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.departament != null) {
                message.departament = data.departament;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                name?: string;
                surname?: string;
                email?: string;
                departament?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.surname != null) {
                data.surname = this.surname;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.departament != null) {
                data.departament = this.departament;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.name.length)
                writer.writeString(2, this.name);
            if (this.surname.length)
                writer.writeString(3, this.surname);
            if (this.email.length)
                writer.writeString(4, this.email);
            if (this.departament.length)
                writer.writeString(5, this.departament);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Admin {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Admin();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.surname = reader.readString();
                        break;
                    case 4:
                        message.email = reader.readString();
                        break;
                    case 5:
                        message.departament = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Admin {
            return Admin.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedAdminServiceService {
        static definition = {
            GetAdmin: {
                path: "/admin.AdminService/GetAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetAdminRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetAdminRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Admin) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Admin.deserialize(new Uint8Array(bytes))
            },
            UpdateAdmin: {
                path: "/admin.AdminService/UpdateAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: UpdateAdminRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => UpdateAdminRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Admin) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Admin.deserialize(new Uint8Array(bytes))
            },
            DeleteAdmin: {
                path: "/admin.AdminService/DeleteAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: DeleteAdminRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => DeleteAdminRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            },
            IsAdmin: {
                path: "/admin.AdminService/IsAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: IsAdminRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => IsAdminRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: IsAdminResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => IsAdminResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetAdmin(call: grpc_1.ServerUnaryCall<GetAdminRequest, Admin>, callback: grpc_1.sendUnaryData<Admin>): void;
        abstract UpdateAdmin(call: grpc_1.ServerUnaryCall<UpdateAdminRequest, Admin>, callback: grpc_1.sendUnaryData<Admin>): void;
        abstract DeleteAdmin(call: grpc_1.ServerUnaryCall<DeleteAdminRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
        abstract IsAdmin(call: grpc_1.ServerUnaryCall<IsAdminRequest, IsAdminResponse>, callback: grpc_1.sendUnaryData<IsAdminResponse>): void;
    }
    export class AdminServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedAdminServiceService.definition, "AdminService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetAdmin: GrpcUnaryServiceInterface<GetAdminRequest, Admin> = (message: GetAdminRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Admin>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Admin>, callback?: grpc_1.requestCallback<Admin>): grpc_1.ClientUnaryCall => {
            return super.GetAdmin(message, metadata, options, callback);
        };
        UpdateAdmin: GrpcUnaryServiceInterface<UpdateAdminRequest, Admin> = (message: UpdateAdminRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Admin>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Admin>, callback?: grpc_1.requestCallback<Admin>): grpc_1.ClientUnaryCall => {
            return super.UpdateAdmin(message, metadata, options, callback);
        };
        DeleteAdmin: GrpcUnaryServiceInterface<DeleteAdminRequest, dependency_1.google.protobuf.Empty> = (message: DeleteAdminRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.DeleteAdmin(message, metadata, options, callback);
        };
        IsAdmin: GrpcUnaryServiceInterface<IsAdminRequest, IsAdminResponse> = (message: IsAdminRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<IsAdminResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<IsAdminResponse>, callback?: grpc_1.requestCallback<IsAdminResponse>): grpc_1.ClientUnaryCall => {
            return super.IsAdmin(message, metadata, options, callback);
        };
    }
}
