/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/user/admin.proto" (package "admin", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AdminService } from "./admin";
import type { IsAdminResponse } from "./admin";
import type { IsAdminRequest } from "./admin";
import type { Empty } from "../../google/protobuf/empty";
import type { DeleteAdminRequest } from "./admin";
import type { UpdateAdminRequest } from "./admin";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Admin } from "./admin";
import type { GetAdminRequest } from "./admin";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис для управления администраторами.
 *
 * @generated from protobuf service admin.AdminService
 */
export interface IAdminServiceClient {
    /**
     * Получает администратора.
     *
     * @generated from protobuf rpc: GetAdmin(admin.GetAdminRequest) returns (admin.Admin);
     */
    getAdmin(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, Admin>;
    /**
     * Обновляет администратора.
     *
     * @generated from protobuf rpc: UpdateAdmin(admin.UpdateAdminRequest) returns (admin.Admin);
     */
    updateAdmin(input: UpdateAdminRequest, options?: RpcOptions): UnaryCall<UpdateAdminRequest, Admin>;
    /**
     * Удаляет администратора.
     *
     * @generated from protobuf rpc: DeleteAdmin(admin.DeleteAdminRequest) returns (google.protobuf.Empty);
     */
    deleteAdmin(input: DeleteAdminRequest, options?: RpcOptions): UnaryCall<DeleteAdminRequest, Empty>;
    /**
     * Проверяет, является ли пользователь администратором.
     *
     * @generated from protobuf rpc: IsAdmin(admin.IsAdminRequest) returns (admin.IsAdminResponse);
     */
    isAdmin(input: IsAdminRequest, options?: RpcOptions): UnaryCall<IsAdminRequest, IsAdminResponse>;
}
/**
 * Сервис для управления администраторами.
 *
 * @generated from protobuf service admin.AdminService
 */
export class AdminServiceClient implements IAdminServiceClient, ServiceInfo {
    typeName = AdminService.typeName;
    methods = AdminService.methods;
    options = AdminService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Получает администратора.
     *
     * @generated from protobuf rpc: GetAdmin(admin.GetAdminRequest) returns (admin.Admin);
     */
    getAdmin(input: GetAdminRequest, options?: RpcOptions): UnaryCall<GetAdminRequest, Admin> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAdminRequest, Admin>("unary", this._transport, method, opt, input);
    }
    /**
     * Обновляет администратора.
     *
     * @generated from protobuf rpc: UpdateAdmin(admin.UpdateAdminRequest) returns (admin.Admin);
     */
    updateAdmin(input: UpdateAdminRequest, options?: RpcOptions): UnaryCall<UpdateAdminRequest, Admin> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAdminRequest, Admin>("unary", this._transport, method, opt, input);
    }
    /**
     * Удаляет администратора.
     *
     * @generated from protobuf rpc: DeleteAdmin(admin.DeleteAdminRequest) returns (google.protobuf.Empty);
     */
    deleteAdmin(input: DeleteAdminRequest, options?: RpcOptions): UnaryCall<DeleteAdminRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAdminRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * Проверяет, является ли пользователь администратором.
     *
     * @generated from protobuf rpc: IsAdmin(admin.IsAdminRequest) returns (admin.IsAdminResponse);
     */
    isAdmin(input: IsAdminRequest, options?: RpcOptions): UnaryCall<IsAdminRequest, IsAdminResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<IsAdminRequest, IsAdminResponse>("unary", this._transport, method, opt, input);
    }
}
