/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/user/employee.proto" (package "employee", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Empty } from "../../google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Запрос на получение пользователя.
 *
 * @generated from protobuf message employee.GetUserRequest
 */
export interface GetUserRequest {
    /**
     * ID пользователя.
     *
     * @generated from protobuf field: string employee_id = 1;
     */
    employeeId: string;
}
/**
 * Запрос на обновление пользователя.
 *
 * Нужно согласовать какие поля расписания можно менять.
 *
 * @generated from protobuf message employee.UpdateUserRequest
 */
export interface UpdateUserRequest {
}
/**
 * Запрос на удаление пользователя.
 *
 * @generated from protobuf message employee.DeleteUserRequest
 */
export interface DeleteUserRequest {
    /**
     * ID пользователя.
     *
     * @generated from protobuf field: string employee_id = 1;
     */
    employeeId: string;
}
/**
 * Структура пользователя.
 *
 * @generated from protobuf message employee.User
 */
export interface User {
    /**
     * ID пользователя.
     *
     * @generated from protobuf field: string id = 1;
     */
    id: string;
    /**
     * Имя пользователя.
     *
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * Отчество пользователя.
     *
     * @generated from protobuf field: string secondName = 3;
     */
    secondName: string;
    /**
     * Фамилия пользователя.
     *
     * @generated from protobuf field: string surname = 4;
     */
    surname: string;
    /**
     * Электронная почта пользователя.
     *
     * @generated from protobuf field: string email = 5;
     */
    email: string;
    /**
     * Возраст пользователя.
     *
     * @generated from protobuf field: uint32 age = 6;
     */
    age: number;
    /**
     * Пол пользователя.
     *
     * @generated from protobuf field: bool sex = 7;
     */
    sex: boolean;
    /**
     * Номер телефона пользователя.
     *
     * @generated from protobuf field: string number = 8;
     */
    number: string;
    /**
     * Отдел пользователя.
     *
     * @generated from protobuf field: string departament = 9;
     */
    departament: string;
    /**
     * Должность пользователя.
     *
     * @generated from protobuf field: string post = 10;
     */
    post: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class GetUserRequest$Type extends MessageType<GetUserRequest> {
    constructor() {
        super("employee.GetUserRequest", [
            { no: 1, name: "employee_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetUserRequest>): GetUserRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.employeeId = "";
        if (value !== undefined)
            reflectionMergePartial<GetUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetUserRequest): GetUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string employee_id */ 1:
                    message.employeeId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string employee_id = 1; */
        if (message.employeeId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.employeeId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message employee.GetUserRequest
 */
export const GetUserRequest = new GetUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateUserRequest$Type extends MessageType<UpdateUserRequest> {
    constructor() {
        super("employee.UpdateUserRequest", []);
    }
    create(value?: PartialMessage<UpdateUserRequest>): UpdateUserRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateUserRequest): UpdateUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message employee.UpdateUserRequest
 */
export const UpdateUserRequest = new UpdateUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteUserRequest$Type extends MessageType<DeleteUserRequest> {
    constructor() {
        super("employee.DeleteUserRequest", [
            { no: 1, name: "employee_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteUserRequest>): DeleteUserRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.employeeId = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteUserRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteUserRequest): DeleteUserRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string employee_id */ 1:
                    message.employeeId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteUserRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string employee_id = 1; */
        if (message.employeeId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.employeeId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message employee.DeleteUserRequest
 */
export const DeleteUserRequest = new DeleteUserRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("employee.User", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "secondName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "surname", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "email", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "age", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "sex", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 8, name: "number", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "departament", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "post", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<User>): User {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.secondName = "";
        message.surname = "";
        message.email = "";
        message.age = 0;
        message.sex = false;
        message.number = "";
        message.departament = "";
        message.post = "";
        if (value !== undefined)
            reflectionMergePartial<User>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User): User {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string secondName */ 3:
                    message.secondName = reader.string();
                    break;
                case /* string surname */ 4:
                    message.surname = reader.string();
                    break;
                case /* string email */ 5:
                    message.email = reader.string();
                    break;
                case /* uint32 age */ 6:
                    message.age = reader.uint32();
                    break;
                case /* bool sex */ 7:
                    message.sex = reader.bool();
                    break;
                case /* string number */ 8:
                    message.number = reader.string();
                    break;
                case /* string departament */ 9:
                    message.departament = reader.string();
                    break;
                case /* string post */ 10:
                    message.post = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string secondName = 3; */
        if (message.secondName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.secondName);
        /* string surname = 4; */
        if (message.surname !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.surname);
        /* string email = 5; */
        if (message.email !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.email);
        /* uint32 age = 6; */
        if (message.age !== 0)
            writer.tag(6, WireType.Varint).uint32(message.age);
        /* bool sex = 7; */
        if (message.sex !== false)
            writer.tag(7, WireType.Varint).bool(message.sex);
        /* string number = 8; */
        if (message.number !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.number);
        /* string departament = 9; */
        if (message.departament !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.departament);
        /* string post = 10; */
        if (message.post !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.post);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message employee.User
 */
export const User = new User$Type();
/**
 * @generated ServiceType for protobuf service employee.EmployeeService
 */
export const EmployeeService = new ServiceType("employee.EmployeeService", [
    { name: "GetUser", options: {}, I: GetUserRequest, O: User },
    { name: "UpdateAdmin", options: {}, I: UpdateUserRequest, O: User },
    { name: "DeleteAdmin", options: {}, I: DeleteUserRequest, O: Empty }
]);
