/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 6.30.2
 * source: v1/user/employee.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./..\\..\\google\\protobuf\\empty";
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace employee {
    export class GetUserRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            employee_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("employee_id" in data && data.employee_id != undefined) {
                    this.employee_id = data.employee_id;
                }
            }
        }
        get employee_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set employee_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            employee_id?: string;
        }): GetUserRequest {
            const message = new GetUserRequest({});
            if (data.employee_id != null) {
                message.employee_id = data.employee_id;
            }
            return message;
        }
        toObject() {
            const data: {
                employee_id?: string;
            } = {};
            if (this.employee_id != null) {
                data.employee_id = this.employee_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.employee_id.length)
                writer.writeString(1, this.employee_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): GetUserRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new GetUserRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.employee_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): GetUserRequest {
            return GetUserRequest.deserialize(bytes);
        }
    }
    export class UpdateUserRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}): UpdateUserRequest {
            const message = new UpdateUserRequest({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): UpdateUserRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new UpdateUserRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): UpdateUserRequest {
            return UpdateUserRequest.deserialize(bytes);
        }
    }
    export class DeleteUserRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            employee_id?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("employee_id" in data && data.employee_id != undefined) {
                    this.employee_id = data.employee_id;
                }
            }
        }
        get employee_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set employee_id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            employee_id?: string;
        }): DeleteUserRequest {
            const message = new DeleteUserRequest({});
            if (data.employee_id != null) {
                message.employee_id = data.employee_id;
            }
            return message;
        }
        toObject() {
            const data: {
                employee_id?: string;
            } = {};
            if (this.employee_id != null) {
                data.employee_id = this.employee_id;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.employee_id.length)
                writer.writeString(1, this.employee_id);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteUserRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteUserRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.employee_id = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteUserRequest {
            return DeleteUserRequest.deserialize(bytes);
        }
    }
    export class User extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: string;
            name?: string;
            secondName?: string;
            surname?: string;
            email?: string;
            age?: number;
            sex?: boolean;
            number?: string;
            departament?: string;
            post?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("secondName" in data && data.secondName != undefined) {
                    this.secondName = data.secondName;
                }
                if ("surname" in data && data.surname != undefined) {
                    this.surname = data.surname;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("age" in data && data.age != undefined) {
                    this.age = data.age;
                }
                if ("sex" in data && data.sex != undefined) {
                    this.sex = data.sex;
                }
                if ("number" in data && data.number != undefined) {
                    this.number = data.number;
                }
                if ("departament" in data && data.departament != undefined) {
                    this.departament = data.departament;
                }
                if ("post" in data && data.post != undefined) {
                    this.post = data.post;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set id(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get secondName() {
            return pb_1.Message.getFieldWithDefault(this, 3, "") as string;
        }
        set secondName(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        get surname() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set surname(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get age() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set age(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get sex() {
            return pb_1.Message.getFieldWithDefault(this, 7, false) as boolean;
        }
        set sex(value: boolean) {
            pb_1.Message.setField(this, 7, value);
        }
        get number() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set number(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        get departament() {
            return pb_1.Message.getFieldWithDefault(this, 9, "") as string;
        }
        set departament(value: string) {
            pb_1.Message.setField(this, 9, value);
        }
        get post() {
            return pb_1.Message.getFieldWithDefault(this, 10, "") as string;
        }
        set post(value: string) {
            pb_1.Message.setField(this, 10, value);
        }
        static fromObject(data: {
            id?: string;
            name?: string;
            secondName?: string;
            surname?: string;
            email?: string;
            age?: number;
            sex?: boolean;
            number?: string;
            departament?: string;
            post?: string;
        }): User {
            const message = new User({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.secondName != null) {
                message.secondName = data.secondName;
            }
            if (data.surname != null) {
                message.surname = data.surname;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.age != null) {
                message.age = data.age;
            }
            if (data.sex != null) {
                message.sex = data.sex;
            }
            if (data.number != null) {
                message.number = data.number;
            }
            if (data.departament != null) {
                message.departament = data.departament;
            }
            if (data.post != null) {
                message.post = data.post;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: string;
                name?: string;
                secondName?: string;
                surname?: string;
                email?: string;
                age?: number;
                sex?: boolean;
                number?: string;
                departament?: string;
                post?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.secondName != null) {
                data.secondName = this.secondName;
            }
            if (this.surname != null) {
                data.surname = this.surname;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.age != null) {
                data.age = this.age;
            }
            if (this.sex != null) {
                data.sex = this.sex;
            }
            if (this.number != null) {
                data.number = this.number;
            }
            if (this.departament != null) {
                data.departament = this.departament;
            }
            if (this.post != null) {
                data.post = this.post;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id.length)
                writer.writeString(1, this.id);
            if (this.name.length)
                writer.writeString(2, this.name);
            if (this.secondName.length)
                writer.writeString(3, this.secondName);
            if (this.surname.length)
                writer.writeString(4, this.surname);
            if (this.email.length)
                writer.writeString(5, this.email);
            if (this.age != 0)
                writer.writeUint32(6, this.age);
            if (this.sex != false)
                writer.writeBool(7, this.sex);
            if (this.number.length)
                writer.writeString(8, this.number);
            if (this.departament.length)
                writer.writeString(9, this.departament);
            if (this.post.length)
                writer.writeString(10, this.post);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): User {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new User();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readString();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.secondName = reader.readString();
                        break;
                    case 4:
                        message.surname = reader.readString();
                        break;
                    case 5:
                        message.email = reader.readString();
                        break;
                    case 6:
                        message.age = reader.readUint32();
                        break;
                    case 7:
                        message.sex = reader.readBool();
                        break;
                    case 8:
                        message.number = reader.readString();
                        break;
                    case 9:
                        message.departament = reader.readString();
                        break;
                    case 10:
                        message.post = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): User {
            return User.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedEmployeeServiceService {
        static definition = {
            GetUser: {
                path: "/employee.EmployeeService/GetUser",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: GetUserRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => GetUserRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: User) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => User.deserialize(new Uint8Array(bytes))
            },
            UpdateAdmin: {
                path: "/employee.EmployeeService/UpdateAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: UpdateUserRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => UpdateUserRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: User) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => User.deserialize(new Uint8Array(bytes))
            },
            DeleteAdmin: {
                path: "/employee.EmployeeService/DeleteAdmin",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: DeleteUserRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => DeleteUserRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: dependency_1.google.protobuf.Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => dependency_1.google.protobuf.Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract GetUser(call: grpc_1.ServerUnaryCall<GetUserRequest, User>, callback: grpc_1.sendUnaryData<User>): void;
        abstract UpdateAdmin(call: grpc_1.ServerUnaryCall<UpdateUserRequest, User>, callback: grpc_1.sendUnaryData<User>): void;
        abstract DeleteAdmin(call: grpc_1.ServerUnaryCall<DeleteUserRequest, dependency_1.google.protobuf.Empty>, callback: grpc_1.sendUnaryData<dependency_1.google.protobuf.Empty>): void;
    }
    export class EmployeeServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedEmployeeServiceService.definition, "EmployeeService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        GetUser: GrpcUnaryServiceInterface<GetUserRequest, User> = (message: GetUserRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<User>, options?: grpc_1.CallOptions | grpc_1.requestCallback<User>, callback?: grpc_1.requestCallback<User>): grpc_1.ClientUnaryCall => {
            return super.GetUser(message, metadata, options, callback);
        };
        UpdateAdmin: GrpcUnaryServiceInterface<UpdateUserRequest, User> = (message: UpdateUserRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<User>, options?: grpc_1.CallOptions | grpc_1.requestCallback<User>, callback?: grpc_1.requestCallback<User>): grpc_1.ClientUnaryCall => {
            return super.UpdateAdmin(message, metadata, options, callback);
        };
        DeleteAdmin: GrpcUnaryServiceInterface<DeleteUserRequest, dependency_1.google.protobuf.Empty> = (message: DeleteUserRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<dependency_1.google.protobuf.Empty>, callback?: grpc_1.requestCallback<dependency_1.google.protobuf.Empty>): grpc_1.ClientUnaryCall => {
            return super.DeleteAdmin(message, metadata, options, callback);
        };
    }
}
