/**
 * @fileoverview gRPC-Web generated client stub for employee
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.2
// source: v1/user/employee.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as v1_user_employee_pb from '../../v1/user/employee_pb'; // proto import: "v1/user/employee.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class EmployeeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetUser = new grpcWeb.MethodDescriptor(
    '/employee.EmployeeService/GetUser',
    grpcWeb.MethodType.UNARY,
    v1_user_employee_pb.GetUserRequest,
    v1_user_employee_pb.User,
    (request: v1_user_employee_pb.GetUserRequest) => {
      return request.serializeBinary();
    },
    v1_user_employee_pb.User.deserializeBinary
  );

  getUser(
    request: v1_user_employee_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_user_employee_pb.User>;

  getUser(
    request: v1_user_employee_pb.GetUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_user_employee_pb.User) => void): grpcWeb.ClientReadableStream<v1_user_employee_pb.User>;

  getUser(
    request: v1_user_employee_pb.GetUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_user_employee_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/employee.EmployeeService/GetUser',
        request,
        metadata || {},
        this.methodDescriptorGetUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/employee.EmployeeService/GetUser',
    request,
    metadata || {},
    this.methodDescriptorGetUser);
  }

  methodDescriptorUpdateAdmin = new grpcWeb.MethodDescriptor(
    '/employee.EmployeeService/UpdateAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_employee_pb.UpdateUserRequest,
    v1_user_employee_pb.User,
    (request: v1_user_employee_pb.UpdateUserRequest) => {
      return request.serializeBinary();
    },
    v1_user_employee_pb.User.deserializeBinary
  );

  updateAdmin(
    request: v1_user_employee_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<v1_user_employee_pb.User>;

  updateAdmin(
    request: v1_user_employee_pb.UpdateUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: v1_user_employee_pb.User) => void): grpcWeb.ClientReadableStream<v1_user_employee_pb.User>;

  updateAdmin(
    request: v1_user_employee_pb.UpdateUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: v1_user_employee_pb.User) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/employee.EmployeeService/UpdateAdmin',
        request,
        metadata || {},
        this.methodDescriptorUpdateAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/employee.EmployeeService/UpdateAdmin',
    request,
    metadata || {},
    this.methodDescriptorUpdateAdmin);
  }

  methodDescriptorDeleteAdmin = new grpcWeb.MethodDescriptor(
    '/employee.EmployeeService/DeleteAdmin',
    grpcWeb.MethodType.UNARY,
    v1_user_employee_pb.DeleteUserRequest,
    google_protobuf_empty_pb.Empty,
    (request: v1_user_employee_pb.DeleteUserRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteAdmin(
    request: v1_user_employee_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteAdmin(
    request: v1_user_employee_pb.DeleteUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteAdmin(
    request: v1_user_employee_pb.DeleteUserRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/employee.EmployeeService/DeleteAdmin',
        request,
        metadata || {},
        this.methodDescriptorDeleteAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/employee.EmployeeService/DeleteAdmin',
    request,
    metadata || {},
    this.methodDescriptorDeleteAdmin);
  }

}

