/* eslint-disable */
// @generated by protobuf-ts 2.10.0 with parameter ts_nocheck,eslint_disable
// @generated from protobuf file "v1/user/employee.proto" (package "employee", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { EmployeeService } from "./employee";
import type { Empty } from "../../google/protobuf/empty";
import type { DeleteUserRequest } from "./employee";
import type { UpdateUserRequest } from "./employee";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { User } from "./employee";
import type { GetUserRequest } from "./employee";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Сервис для управления пользователями.
 *
 * @generated from protobuf service employee.EmployeeService
 */
export interface IEmployeeServiceClient {
    /**
     * Получает пользователя.
     *
     * @generated from protobuf rpc: GetUser(employee.GetUserRequest) returns (employee.User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User>;
    /**
     * Обновляет пользователя.
     *
     * @generated from protobuf rpc: UpdateAdmin(employee.UpdateUserRequest) returns (employee.User);
     */
    updateAdmin(input: UpdateUserRequest, options?: RpcOptions): UnaryCall<UpdateUserRequest, User>;
    /**
     * Удаляет пользователя.
     *
     * @generated from protobuf rpc: DeleteAdmin(employee.DeleteUserRequest) returns (google.protobuf.Empty);
     */
    deleteAdmin(input: DeleteUserRequest, options?: RpcOptions): UnaryCall<DeleteUserRequest, Empty>;
}
/**
 * Сервис для управления пользователями.
 *
 * @generated from protobuf service employee.EmployeeService
 */
export class EmployeeServiceClient implements IEmployeeServiceClient, ServiceInfo {
    typeName = EmployeeService.typeName;
    methods = EmployeeService.methods;
    options = EmployeeService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Получает пользователя.
     *
     * @generated from protobuf rpc: GetUser(employee.GetUserRequest) returns (employee.User);
     */
    getUser(input: GetUserRequest, options?: RpcOptions): UnaryCall<GetUserRequest, User> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetUserRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * Обновляет пользователя.
     *
     * @generated from protobuf rpc: UpdateAdmin(employee.UpdateUserRequest) returns (employee.User);
     */
    updateAdmin(input: UpdateUserRequest, options?: RpcOptions): UnaryCall<UpdateUserRequest, User> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateUserRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * Удаляет пользователя.
     *
     * @generated from protobuf rpc: DeleteAdmin(employee.DeleteUserRequest) returns (google.protobuf.Empty);
     */
    deleteAdmin(input: DeleteUserRequest, options?: RpcOptions): UnaryCall<DeleteUserRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteUserRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
